baseURL = '//darren.codes/'
languageCode = 'en-gb'
title = 'Darren Burns'
theme = "archie"

copyright = "© Darren Burns"

# disqusShortname = "yourDisqusShortname"

paginate=8 # articles per page

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=true # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Hey, I'm Darren. I'm a software engineer in Edinburgh, UK. I enjoy working on open-source developer tooling, and occasionally writing about it here."
	mathjax = false # enable MathJax support
	katex = false # enable KaTeX support

[markup]
  [markup.highlight]
    codeFences = true
    codeFencesGuessSyntax = true
	style = "catppuccin-mocha"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/darrenburns/"

[[params.social]]
name = "X"
icon = "twitter"
url = "https://x.com/_darrenburns"

[[params.social]]
name = "Fosstodon"
icon = "message-circle"
url = "https://fosstodon.org/@darrenburns"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Likes"
url = "/likes"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[services.rss]
limit = 20 # or however many posts you want in the feed
fullContent = true # this is the key setting to include full articles
